/* Generated by AN DISI Unibo */ 
package it.unibo.driverobot;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.ActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.planned.QActorPlanned;
import it.unibo.qactors.action.ActionDummy;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.iot.configurator.Configurator;
import it.unibo.iot.executors.baseRobot.IBaseRobot; 
import it.unibo.iot.models.sensorData.distance.IDistanceSensorData;
import it.unibo.iot.models.sensorData.line.ILineSensorData;
import it.unibo.iot.models.sensorData.magnetometer.IMagnetometerSensorData;
import it.unibo.iot.sensors.ISensor; 
import it.unibo.iot.sensors.ISensorObserver;
import it.unibo.iot.sensors.distanceSensor.DistanceSensor;
import it.unibo.iot.sensors.lineSensor.LineSensor;
import it.unibo.iot.sensors.magnetometerSensor.MagnetometerSensor;

public class AbstractDriverobot extends it.unibo.qactor.robot.RobotActor { 
protected AsynchActionResult aar = null;
protected boolean actionResult = true;
protected alice.tuprolog.SolveInfo sol;

		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}


	public AbstractDriverobot(String actorId, ActorContext myCtx, IOutputEnvView outEnvView ,it.unibo.iot.executors.baseRobot.IBaseRobot baserobot)  throws Exception{
		super(actorId, myCtx, "./srcMore/it/unibo/driverobot/plans.txt", 
		"./srcMore/it/unibo/driverobot/WorldTheory.pl",
		setTheEnv( outEnvView ) ,baserobot , "init");		
 	}
	@Override
	protected void doJob() throws Exception {
 		initSensorSystem();
		boolean res = init();
		//println(getName() + " doJob " + res );
	} 
	/* 
	* ------------------------------------------------------------
	* PLANS
	* ------------------------------------------------------------
	*/
    public boolean init() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "init";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"driverobot starts\" ";
    		println( temporaryStr );  
    		{ String parg = "consult( \"talkTheory.pl\" )";
    		  aar = solveGoal( parg , 0, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "init";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! switchToPlan("prologFailure").getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		if( ! switchToPlan("drive").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean drive() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "drive";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		//ReceiveMsg
    		 		 aar = receiveAMsg(600000, "obstacle" , "detect" ); 	//could block
    				if( aar.getInterrupted() ){
    					curPlanInExec   = "playTheGame";
    					if( ! aar.getGoon() ) break;
    				} 			
    				if( ! aar.getGoon() ){
    					System.out.println("			WARNING: receiveMsg in " + getName() + " TOUT " + aar.getTimeRemained() + "/" +  600000);
    					addRule("tout(receive,"+getName()+")");
    				} 		 
    				//println(getName() + " received " + aar.getResult() );
    		//onMsg
    		if( currentMessage.msgId().equals("drive") ){
    			String parg="saveMove(X)";
    			parg = updateVars(null, Term.createTerm("drive(X)"), Term.createTerm("drive(X)"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ) {
    					aar = solveGoal( parg , 0, "","" , "");
    					//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    					if( aar.getInterrupted() ){
    						curPlanInExec   = "drive";
    						if( ! aar.getGoon() ) break;
    					} 			
    					if( aar.getResult().equals("failure")){
    						if( ! aar.getGoon() ) break;
    					}else if( ! aar.getGoon() ) break;
    				}
    		}//onMsg
    		if( currentMessage.msgId().equals("drive") ){
    			String parg="X";
    			parg = updateVars(null, Term.createTerm("drive(X)"), Term.createTerm("drive(X)"), 
    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
    				if( parg != null ) {
    					aar = solveGoal( parg , 0, "","" , "");
    					//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    					if( aar.getInterrupted() ){
    						curPlanInExec   = "drive";
    						if( ! aar.getGoon() ) break;
    					} 			
    					if( aar.getResult().equals("failure")){
    						if( ! aar.getGoon() ) break;
    					}else if( ! aar.getGoon() ) break;
    				}
    		}if( repeatPlan(0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean detect() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "detect";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Stopping...\" ";
    		println( temporaryStr );  
    		//stop
    		if( ! execRobotMove("detect","stop",100,0,1000, "" , "") ) break;
    		temporaryStr = unifyMsgContent("bagFound","bagFound", guardVars ).toString();
    		emit( "bagFound", temporaryStr );
    		{ String parg = "startBlink";
    		  aar = solveGoal( parg , 0, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "detect";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		temporaryStr = " \"Starting detection Phase...\" ";
    		println( temporaryStr );  
    		if( (guardVars = evalTheGuard( " !?detect(X)" )) != null ){
    		temporaryStr = unifyMsgContent("detectionResults(X)","detectionResults(X)", guardVars ).toString();
    		sendMsg("detectionResults","asc", ActorContext.dispatch, temporaryStr ); 
    		}
    		temporaryStr = " \"Detection Results Sent\" ";
    		println( temporaryStr );  
    		{ String parg = "stopBlink";
    		  aar = solveGoal( parg , 0, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "detect";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		temporaryStr = " \"Back to base\" ";
    		println( temporaryStr );  
    		if( ! switchToPlan("backToBase").getGoon() ) break;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean backToBase() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "backToBase";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		if( (guardVars = evalTheGuard( " !?arrivedToBase" )) != null ){
    		if( ! switchToPlan("finish").getGoon() ) break;
    		}
    		if( (guardVars = evalTheGuard( " !?nextInversedMove(X)" )) != null ){
    		{ String parg = "X";
    		parg = substituteVars(guardVars,parg);
    		  aar = solveGoal( parg , 0, "","alarm" , "alarmReaction" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "backToBase";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		}
    		if( repeatPlan(0).getGoon() ) continue;
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean alarmReaction() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "alarmReaction";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		{ String parg = "startBlink";
    		  aar = solveGoal( parg , 0, "","" , "" );
    		//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
    		if( aar.getInterrupted() ){
    			curPlanInExec   = "alarmReaction";
    			if( ! aar.getGoon() ) break;
    		} 			
    		if( aar.getResult().equals("failure")){
    		if( ! aar.getGoon() ) break;
    		}else if( ! aar.getGoon() ) break;
    		}
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean finish() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "finish";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"DriveRobot ends\" ";
    		println( temporaryStr );  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    public boolean prologFailure() throws Exception{	//public to allow reflection
    try{
    	curPlanInExec =  "prologFailure";
    	boolean returnValue = suspendWork;
    while(true){
    nPlanIter++;
    		temporaryStr = " \"Failed to load talkTheory\" ";
    		println( temporaryStr );  
    		returnValue = continueWork;  
    break;
    }//while
    return returnValue;
    }catch(Exception e){
    println( getName() + " ERROR " + e.getMessage() );
    throw e;
    }
    }
    /* 
    * ------------------------------------------------------------
    * SENSORS
    * ------------------------------------------------------------
    */
    protected void initSensorSystem(){		
    	try {
    		String goal = "consult( \"./src/it/unibo/driverobot/sensorTheory.pl\" )";
    		AsynchActionResult aar = solveGoal( goal , 0, "","" , "" );
    		if(  aar.getResult().contains("failure")){
    			//println( "avatar initSensorSystem attempt to load sensorTheory "  );
    			goal = "consult( \"./sensorTheory.pl\" )";
    			aar = solveGoal( goal , 0, "","" , "" );
    			//println( "avatar initSensorSystem= "  +  aar.getResult() );
    		}
    		addSensorObservers();
    	} catch (Exception e) {
    		e.printStackTrace();
    	}
    }
    /*
    //COMPONENTS
     RobotComponent motorleft 
     RobotComponent motorright 
    sensor distanceRadar  todo  
    Composed component motors
    */
    protected void addSensorObservers(){
    	for (ISensor<?> sensor : Configurator.getInstance().getSensors()) {
    		//println( "driverobot sensor= "  + sensor.getDefStringRep() );
    		//println( "driverobot sensor class= "  + sensor.getClass().getName() );
        	if( sensor instanceof DistanceSensor){
        		DistanceSensor sensorDistance  = (DistanceSensor) sensor;
        		ISensorObserver<IDistanceSensorData> obs = new SensorObserver<IDistanceSensorData>(this,outView);
        //		println( "avatar add observer to  "  + sensorDistance.getDefStringRep() );
        		sensorDistance.addObserver(  obs  ) ;
        	}
        	if( sensor instanceof LineSensor){
        		LineSensor sensorLine = (LineSensor) sensor;
         		ISensorObserver<ILineSensorData> obs = new SensorObserver<ILineSensorData>(this,outView);
        //		println( "avatar add observer to  "  + sensorLine.getDefStringRep() );
        		sensorLine.addObserver(  obs  ) ;
        	}
         	if( sensor instanceof MagnetometerSensor){
        		MagnetometerSensor sensorMagneto = (MagnetometerSensor) sensor;
         		ISensorObserver<IMagnetometerSensorData> obs = new SensorObserver<IMagnetometerSensorData>(this,outView);
        //		println( "avatar add observer to  "  + sensorMagneto.getDefStringRep() );
        		sensorMagneto.addObserver(  obs  ) ;
        	}
    	//OLD	
    	}		
    }	
    
 
	/* 
	* ------------------------------------------------------------
	* APPLICATION ACTIONS
	* ------------------------------------------------------------
	*/
	
  }

