/* Generated by AN DISI Unibo */ 
package it.unibo.removerobot;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;
public class Removerobot extends AbstractRemoverobot { 
	public Removerobot(String actorId, ActorContext myCtx, IOutputEnvView outEnvView ,it.unibo.iot.executors.baseRobot.IBaseRobot baserobot) throws Exception{
		super(actorId,myCtx,outEnvView ,baserobot );
	}
}
