/* Generated by AN DISI Unibo */ 
package it.unibo.ctxLocal;
import it.unibo.qactors.ActorContext;
import java.io.InputStream;
import alice.tuprolog.SolveInfo;
import alice.tuprolog.Term;
import alice.tuprolog.Var;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IBasicEnvAwt;
import it.unibo.is.interfaces.IIntent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;

public class MainCtxLocal extends ActorContext implements IActivity{
private IBasicEnvAwt env; 
private it.unibo.qactor.robot.RobotActor robot; 
 
	public MainCtxLocal(String name, IOutputEnvView outEnvView,
			InputStream sysKbStream, InputStream sysRulesStream) throws Exception {
		super(name, outEnvView, sysKbStream, sysRulesStream);
		this.outEnvView = outEnvView;
		env = outEnvView.getEnv();
 	}
	@Override
	public void configure() {
		try {
				IBasicEnvAwt env = outEnvView.getEnv();
				if( env != null){
 					env.addInputPanel(60);
					env.addCmdPanel("input", new String[]{"INPUT"}, this);					
				}
		println("Starting the baseRobot (two robots cannot run in the same context).... ");
		it.unibo.iot.executors.baseRobot.IBaseRobot baseRobot = 
				it.unibo.qactor.robot.RobotSysKb.setRobotBase(this,  "plexiBox" );
		Thread.sleep(300); //Give time to the baseRobot to start
		robot= new it.unibo.driverobot.Driverobot("driverobot", this, outEnvView, baseRobot);
//			new it.unibo.driverobot.Driverobot("driverobot", this, outEnvView, baseRobot);
		println("Starting the handlers .... ");
		println("Starting the actors .... ");
new it.unibo.operator.Operator("operator", this, outEnvView);
new it.unibo.asc.Asc("asc", this, outEnvView);
		
 		} catch (Exception e) {
 		  e.printStackTrace();
		} 		
	}
	@Override
	public void execAction(String cmd) {
		String input = env.readln();
		//println("input=" + input);
		try {
			Term.createTerm(input);
			String goal = "executeInput(" + input +").";
			SolveInfo sol = robot.getPrologEngine().solve( goal );
			println("> " + sol);
		} catch (Exception e) {
 			println("Input error " + e.getMessage());
		}
 	}
	@Override
	public void execAction() {}
	@Override
	public void execAction(IIntent input) {}
	@Override
	public String execActionWithAnswer(String cmd) {return null;}
 
	
/*
* ----------------------------------------------
* MAIN
* ----------------------------------------------
*/
	public static void main(String[] args) throws Exception{
		IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
 		InputStream sysKbStream    = //MainCtxLocal.class.getResourceAsStream("testcase2016analysis.pl");
 			new java.io.FileInputStream("./srcMore/it/unibo/ctxLocal/testcase2016analysis.pl");
		InputStream sysRulesStream = MainCtxLocal.class.getResourceAsStream("sysRules.pl");
		new MainCtxLocal("ctxLocal", outEnvView, sysKbStream, sysRulesStream ).configure();
 	}
}
