/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.operator;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class Operator extends AbstractOperator { 
	public Operator(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
