/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.obstacleemitter;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;

public class Obstacleemitter extends AbstractObstacleemitter { 
	public Obstacleemitter(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
}
