/* Generated by AN DISI Unibo */ 
package it.unibo.driverobot;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.Base64;

import javax.imageio.ImageIO;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.ActorContext;
import it.unibo.sartiballanti.camera.CameraFactory;
public class Driverobot extends AbstractDriverobot { 
	public Driverobot(String actorId, ActorContext myCtx, IOutputEnvView outEnvView ,it.unibo.iot.executors.baseRobot.IBaseRobot baserobot) throws Exception{
		super(actorId,myCtx,outEnvView ,baserobot );
	}
	
	public String takeStringifiedPhoto(){
		
		BufferedImage img = CameraFactory.getInstance().getCamera().takePhoto();
		
		ByteArrayOutputStream bos = new ByteArrayOutputStream();
		try {
			ImageIO.write(img, "jpg", bos);
			
			byte[] byteArray = bos.toByteArray();
			
			return Base64.getEncoder().encodeToString(byteArray);
			
		} catch (IOException e) {
			e.printStackTrace();
			return "";
		}
	}
	
}
