/* Generated by AN DISI Unibo */ 
package it.unibo.asc;
import alice.tuprolog.Term;
import alice.tuprolog.Struct;
import it.unibo.qactors.ActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.planned.QActorPlanned;
import it.unibo.qactors.action.ActionDummy;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;

public abstract class AbstractAsc extends QActorPlanned { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	
			protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
				return outEnvView;
			}
	
	
		public AbstractAsc(String actorId, ActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx, "./srcMore/it/unibo/asc/plans.txt", 
			"./srcMore/it/unibo/asc/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
	 	}
		@Override
		protected void doJob() throws Exception {
	 		initSensorSystem();
			boolean res = init();
			//println(getName() + " doJob " + res );
		} 
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/
	    public boolean init() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "init";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"ASC starts\" ";
	    		println( temporaryStr );  
	    		if( ! switchToPlan("waitForResults").getGoon() ) break;
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean waitForResults() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "waitForResults";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		//ReceiveMsg
	    		 		 aar = receiveAMsg(600000, "" , "" ); 	//could block
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "playTheGame";
	    					if( ! aar.getGoon() ) break;
	    				} 			
	    				if( ! aar.getGoon() ){
	    					System.out.println("			WARNING: receiveMsg in " + getName() + " TOUT " + aar.getTimeRemained() + "/" +  600000);
	    					addRule("tout(receive,"+getName()+")");
	    				} 		 
	    				//println(getName() + " received " + aar.getResult() );
	    		//onMsg
	    		if( currentMessage.msgId().equals("detectionResults") ){
	    			String parg = "detectionResults(X)";
	    			parg = updateVars(null, Term.createTerm("detectionResults(X)"), Term.createTerm("detectionResults(X)"), 
	    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    				if( parg != null ) println( parg );  
	    		}//onMsg
	    		if( currentMessage.msgId().equals("detectionResults") ){
	    			String parg = "";
	    			parg = updateVars(null, Term.createTerm("detectionResults(X)"), Term.createTerm("detectionResults(X)"), 
	    				    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    				if( parg != null ){
	    					 if( ! switchToPlan("riskDecision").getGoon() ) break; 
	    				}//else println("guard  fails");  //parg is null when there is no guard (onEvent)
	    		}
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    public boolean riskDecision() throws Exception{	//public to allow reflection
	    try{
	    	curPlanInExec =  "riskDecision";
	    	boolean returnValue = suspendWork;
	    while(true){
	    nPlanIter++;
	    		temporaryStr = " \"Evaluating risks\" ";
	    		println( temporaryStr );  
	    		//delay
	    		aar = delayReactive(3000,"" , "");
	    		if( aar.getInterrupted() ) curPlanInExec   = "riskDecision";
	    		if( ! aar.getGoon() ) break;
	    		temporaryStr = unifyMsgContent("alarm","alarm", guardVars ).toString();
	    		emit( "alarm", temporaryStr );
	    break;
	    }//while
	    return returnValue;
	    }catch(Exception e){
	    println( getName() + " ERROR " + e.getMessage() );
	    throw e;
	    }
	    }
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	    
	 
		/* 
		* ------------------------------------------------------------
		* APPLICATION ACTIONS
		* ------------------------------------------------------------
		*/
		
	  }
	
